version: '3'

services:
  backend:
    container_name: mec_bot
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Yekaterinburg
    restart: always
    ports:
      - "3030:3030"
